version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data/
  backend:
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - media:/opt/logs_proc/media
      - staticfiles:/opt/logs_proc/staticfiles
volumes:
  db-data:
  media:
  staticfiles:
