# Generated by Django 2.1.5 on 2019-02-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('datetime', models.DateTimeField()),
                ('method', models.CharField(max_length=8)),
                ('uri', models.CharField(max_length=300)),
                ('status_code', models.SmallIntegerField()),
                ('body_size', models.IntegerField()),
                ('user_agent', models.CharField(max_length=300)),
            ],
        ),
    ]
