# Generated by Django 2.1.5 on 2019-02-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logitem',
            index=models.Index(fields=['datetime'], name='datetime_idx'),
        ),
    ]
